import { useEffect, useState, useRef, type FormEvent } from 'react'
import { ArrowUpRight, Plus, X, FileText, LayoutDashboard, ListChecks, Clock, CircleHelp, MessageSquare, History, ChevronRight, LogOut } from 'lucide-react'
import ServiceHealth from './components/ServiceHealth'
import { pages, readPage } from './pages/navigation'
import { api, type Brief, type Task, type Source, type Conflict } from './services/api'
const localNow = () => { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60000).toISOString().slice(0, 16) + ':00' }
const ASSIGNMENT_AS_OF = '2026-09-25T09:00:00'
type Scope = 'assignment' | 'personal'
const icons = [LayoutDashboard, ListChecks, Clock, CircleHelp, Plus, FileText, MessageSquare, History]
const questions = ['What did I promise Raghav?', 'What needs action today?', 'Who owns the Mumbai lease renewal?', 'Did Divya send the expense report?', 'Did the Meridian call happen?']
const label = (value: string) => value.toLowerCase().replaceAll('_', ' ')
const deadline = (task: Task) => { const latest = task.deadline_history.filter(d => d.accepted).at(-1); return latest?.deadline_text.toLowerCase().includes('morning') ? `${date(task.current_deadline).split(',')[0]} - morning` : date(task.current_deadline) }
const date = (value: string | null) => value ? new Date(value).toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) : 'No confirmed deadline'
function Empty() { return <div className="empty"><strong>No actions yet.</strong><p>Add an email, meeting note or voice note.</p><a href="#add-source">Add Source <ArrowUpRight size={14} /></a></div> }
function TaskCards({ tasks, open }: { tasks: Task[]; open: (task: Task) => void }) {
  return tasks.length ? <div className="task-list">{tasks.map(t => <article className="task-card" key={t.task_id}><div className="task-top"><span className={`badge ${t.status.toLowerCase()}`}>{label(t.status)}</span><span className="muted">{t.source_ids.length} sources</span></div><h3>{t.canonical_title}</h3><div className="task-meta"><span>Owner <b>{t.owner || 'Unconfirmed'}</b></span><span>Deadline <b>{deadline(t)}</b></span>{t.counterparties.length > 0 && <span>With <b>{t.counterparties.join(', ')}</b></span>}</div><div className="task-actions"><button onClick={() => open(t)}>View Evidence <ChevronRight size={14} /></button><button onClick={() => open(t)}>Why this status?</button></div></article>)}</div> : <Empty />
}
export default function App({ onLogout }: { onLogout: () => void }) {
  const [active, setActive] = useState(readPage)
  const [scope, setScope] = useState<Scope>('assignment')
  const scopeRef = useRef(scope); scopeRef.current = scope
  const [asOf, setAsOf] = useState(ASSIGNMENT_AS_OF)
  const [brief, setBrief] = useState<Brief | null>(null)
  const [tasks, setTasks] = useState<Task[]>([])
  const [sources, setSources] = useState<Source[]>([])
  const [audit, setAudit] = useState<{ audit_id: string; event: string; entity_id: string; created_at: string }[]>([])
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)
  const [refresh, setRefresh] = useState(0)
  const [selected, setSelected] = useState<Task | null>(null)
  const [sourceView, setSourceView] = useState<Source | null>(null)
  const [busy, setBusy] = useState(false)
  const [result, setResult] = useState<Task[]>([])
  const [notice, setNotice] = useState('')
  const [resultAsOf, setResultAsOf] = useState('')
  const [form, setForm] = useState(() => ({ source_type: 'MEETING', timestamp: localNow().slice(0, 16), author: 'Arjun Malhotra', recipients: '', subject: '', content: '' }))
  const [timestampEdited, setTimestampEdited] = useState(false)
  useEffect(() => { if (active === 'add-source' && !timestampEdited) setForm(current => ({ ...current, timestamp: localNow().slice(0, 16) })) }, [active, timestampEdited])
  const [question, setQuestion] = useState('')
  const [answer, setAnswer] = useState<{ answer: string; citations: { source_id: string; evidence_text: string }[] } | null>(null)
  useEffect(() => { const change = () => { setActive(readPage()); setError(''); setNotice('') }; window.addEventListener('hashchange', change); return () => window.removeEventListener('hashchange', change) }, [])
  useEffect(() => { const close = (e: KeyboardEvent) => { if (e.key === 'Escape') { setSelected(null); setSourceView(null) } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close) }, [])
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('')
    Promise.all([api<Brief>(`/brief?as_of=${asOf}&scope=${scope}`, undefined, controller.signal), api<Task[]>(`/tasks?as_of=${asOf}&scope=${scope}`, undefined, controller.signal), api<Source[]>(`/sources?scope=${scope}`,  undefined, controller.signal), api<typeof audit>(`/audit?scope=${scope}`,  undefined, controller.signal)])
      .then(([b, t, s, a]) => { if (controller.signal.aborted) return; setBrief(b); setTasks(t); setSources(s); setAudit(a) }).catch(e => { if (!controller.signal.aborted) setError(e.message) }).finally(() => { if (!controller.signal.aborted) setLoading(false) })
    return () => controller.abort()
  }, [asOf, refresh, scope])
  const changeScope = (next: Scope) => {
    setScope(next); setAsOf(next === 'assignment' ? ASSIGNMENT_AS_OF : localNow())
    setBrief(null); setTasks([]); setSources([]); setAudit([]); setAnswer(null); setResult([]); setResultAsOf(''); setNotice(''); setSelected(null); setSourceView(null); setRefresh(v => v + 1)
  }
  useEffect(() => { if (active === 'add-source') changeScope('personal') }, [active])
  const open = (task: Task) => { setSourceView(null); setSelected(task) }
  const openSource = async (id: string) => { try { setSourceView(await api<Source>(`/sources/${encodeURIComponent(id)}`)) } catch(e) { setError((e as Error).message) } }
  const submit = async (e: FormEvent) => {
    e.preventDefault(); setBusy(true); setError(''); setNotice(''); setResult([]); setResultAsOf('')
    try { const data = await api<{ message?: string; duplicate?: boolean; as_of?: string; processing_status: string; affected_tasks: Task[] }>(`/sources?as_of=${asOf}`, { ...form, recipients: form.recipients.split(',').map(s => s.trim()).filter(Boolean) }); setResult(data.affected_tasks); setResultAsOf(data.as_of || ''); if (data.processing_status === 'PROCESSED') { setScope('personal'); setAsOf(data.as_of || localNow()) } setNotice(data.message || `${data.duplicate ? 'Source already processed. Saved results loaded without another AI request.' : 'Source processed.'} ${data.affected_tasks.length} actions found.`); setRefresh(v => v + 1) } catch(e) { setError((e as Error).message) } finally { setBusy(false) }
  }
  const ask = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); setAnswer(null); try { const response = await api<{ answer: string; citations: { source_id: string; evidence_text: string }[] }>('/chat', { question, as_of: asOf, scope }); if (scopeRef.current === scope) setAnswer(response) } catch(e) { setError((e as Error).message) } finally { setBusy(false) } }
  const section = (title: string, items: Task[]) => <section className="brief-section" key={title}><div className="section-title"><h2>{title}</h2><span>{items.length}</span></div><TaskCards tasks={items} open={open} /></section>
  const current = pages.find(p => p.id === active)!
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#daily-brief"><span className="brand-mark">E</span>ExecFlow<span>AI</span></a><p className="brand-sub">Your executive action copilot</p><a href="#add-source" className="add-source" aria-current={active === 'add-source' ? 'page' : undefined}><Plus size={18} /> Add Source</a><span className="nav-label">WORKSPACE</span><nav aria-label="Main navigation">{pages.map((p, i) => { if (p.id === 'add-source') return null; const Icon = icons[i]; return <a key={p.id} href={`#${p.id}`} className={active === p.id ? 'active' : ''} aria-current={active === p.id ? 'page' : undefined}><Icon size={18}/>{p.title}</a> })}</nav><div className="profile"><span className="avatar">AM</span><div><strong>Arjun Malhotra</strong><small>VP Sales</small></div><button className="logout-button" onClick={onLogout} aria-label="Sign out" title="Sign out"><LogOut size={17}/></button></div></aside><main><div className="topbar"><span>Workspace <ChevronRight size={14} /> {current.title}</span><ServiceHealth /></div><div className="page"><header className="page-header"><div><p className="eyebrow">YOUR COMMITMENTS, IN FOCUS</p><h1>{active === 'daily-brief' ? 'Good morning, Arjun' : current.title}</h1><p>{active === 'daily-brief' ? `Here is what needs your attention as of ${new Date(asOf).toLocaleDateString('en-GB', {day: 'numeric', month: 'short', year: 'numeric'})}.` : current.description}</p></div><div className="view-controls"><label className="reference">Workspace<select aria-label="Workspace" value={scope} onChange={e => changeScope(e.target.value as Scope)}><option value="assignment">Assignment 1</option><option value="personal">My Sources</option></select></label><label className="reference">Reference time<input aria-label="Reference time" type="datetime-local" value={asOf.slice(0,16)} onChange={e => { if(e.target.value) setAsOf(e.target.value + ':00') }} /></label></div></header>
    <p className="scope-note">{scope === 'assignment' ? 'Assignment 1: original data pack, 21-25 September 2026.' : 'My Sources: your added emails, notes and commitments.'}</p>
    {error && <div className="error" role="alert">{error}<button onClick={() => setRefresh(v => v+1)}>Refresh data</button></div>}
    {loading && <p className="muted" role="status">Loading workspace…</p>}
    {active === 'daily-brief' && brief && <><div className="metrics">{[['overdue','Overdue'],['due_today','Due Today'],['waiting','Waiting'],['ownership_unclear','Ownership Unclear'],['recently_resolved','Recently Resolved']].map(([key,title]) => <div className={`metric metric-${key}`} key={key}><span>{title}</span><strong>{brief.metrics[key] ?? 0}</strong><small>{key === 'recently_resolved' ? 'Evidence confirmed' : 'At reference time'}</small></div>)}</div><div className="attention"><div><h2>Needs Attention</h2><p>Prioritize overdue promises and confirm who owns the open decisions.</p></div><a href="#my-actions">View my actions <ArrowUpRight size={16}/></a></div>{section('Overdue',brief.sections.overdue)}{section('Due Today',brief.sections.due_today)}{section('Waiting on Others',brief.sections.waiting_on_others)}{section('Ownership Unclear',brief.sections.ownership_unclear)}{section('Completion Unverified',brief.sections.completion_unverified)}{section('Recently Resolved',brief.sections.recently_resolved)}<section className="brief-section"><div className="section-title"><h2>Schedule Conflicts</h2><span>{brief.sections.schedule_conflicts.length}</span></div>{brief.sections.schedule_conflicts.map((c: Conflict,i: number) => <article className="conflict" key={i}><Clock size={20}/><div><strong>{c.event_a.title} / {c.event_b.title}</strong><p>{date(c.overlap_start)}–{date(c.overlap_end)} · {c.overlap_minutes} minute overlap</p><small>Scheduled events; attendance is unverified.</small></div></article>)}</section></>}
    {['my-actions','waiting-on-others','unclear-ownership'].includes(active) && <TaskCards tasks={tasks.filter(t => t.classification === ({'my-actions':'MY_ACTION','waiting-on-others':'WAITING_ON_OTHERS','unclear-ownership':'OWNERSHIP_UNCLEAR'} as Record<string,string>)[active])} open={open} />}
    {active === 'add-source' && <><form className="form-panel" onSubmit={submit}><div className="form-heading"><div><h2>A new source, a clearer next step</h2><p>Paste the original text. ExecFlow identifies actions and keeps the evidence.</p></div></div><div className="form-grid"><label>Source Type<select value={form.source_type} onChange={e=>setForm({...form,source_type:e.target.value})}>{['EMAIL','MEETING','VOICE_NOTE','CALENDAR','NOTE','OTHER'].map(s=><option key={s}>{s}</option>)}</select></label><label>Timestamp<input type="datetime-local" required value={form.timestamp} onChange={e=>{setTimestampEdited(true);setForm({...form,timestamp:e.target.value})}}/></label><label>Author<input required value={form.author} onChange={e=>setForm({...form,author:e.target.value})}/></label><label>Recipients (optional)<input placeholder="Names, separated by commas" value={form.recipients} onChange={e=>setForm({...form,recipients:e.target.value})}/></label></div><label>Subject (optional)<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Content<textarea aria-label="Content" required rows={9} placeholder="Paste an email, meeting note or voice note…" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label><button className="primary" disabled={busy}>{busy ? 'Processing source…' : 'Process with ExecFlow'}<ArrowUpRight size={17}/></button></form>{notice && <p className="notice" role="status">{notice}</p>}{resultAsOf > asOf && <p className="notice">This source is later than your reference time. <button className="secondary" onClick={() => setAsOf(resultAsOf)}>Show workspace as of {date(resultAsOf)}</button></p>}{result.length > 0 && <><h2 className="result-heading">Affected actions</h2><TaskCards tasks={result} open={open}/></>}</>}
    {active === 'sources' && <div className="source-list">{sources.map(s=><button className="source-row" onClick={()=>openSource(s.source_id)} key={s.source_id}><FileText size={20}/><div><strong>{s.subject || 'Untitled source'}</strong><p>{s.author} · {date(s.timestamp)}</p></div><span className="badge">{label(s.source_type)}</span><small>{s.processing_status}</small><ChevronRight size={18}/></button>)}</div>}
    {active === 'ask-execflow' && <div className="chat-panel"><div className="chat-intro"><MessageSquare size={28}/><h2>Ask about the commitments behind your day.</h2><p>Answers grounded in your sources, with evidence you can inspect.</p></div><div className="suggestions">{questions.map(q=><button key={q} onClick={()=>setQuestion(q)}>{q}<ArrowUpRight size={15}/></button>)}</div><form onSubmit={ask}><label>Your question<textarea aria-label="Your question" required rows={3} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What would you like to know?"/></label><button className="primary" disabled={busy}>{busy ? 'Checking evidence…' : 'Ask ExecFlow'}<ArrowUpRight size={16}/></button></form>{answer && <article className="answer"><span className="eyebrow">EXECFLOW ANSWER</span><p>{answer.answer}</p>{answer.citations.map((c,i)=><button className="citation" key={i} onClick={()=>openSource(c.source_id)}><FileText size={16}/><span>“{c.evidence_text}”<small>{c.source_id}</small></span></button>)}</article>}</div>}
    {active === 'audit-trail' && <div className="audit-list">{audit.map(a=><article key={a.audit_id}><History size={18}/><div><strong>{label(a.event)}</strong><p>{a.entity_id}</p></div><time>{date(a.created_at)}</time></article>)}</div>}
  </div></main>{(selected || sourceView) && <div className="drawer-backdrop" onClick={()=>{setSelected(null);setSourceView(null)}}><aside className="drawer" role="dialog" aria-modal="true" aria-label="Evidence" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close evidence" onClick={()=>{setSelected(null);setSourceView(null)}} autoFocus><X/></button><p className="eyebrow">EVIDENCE & DECISIONS</p>{sourceView ? <><h2>{sourceView.subject || 'Source'}</h2><p>{sourceView.source_type} · {date(sourceView.timestamp)} · {sourceView.author}</p><pre>{sourceView.content}</pre>{selected && <button className="secondary" onClick={()=>setSourceView(null)}>Back to task evidence</button>}</> : selected && <><h2>{selected.canonical_title}</h2><span className={`badge ${selected.status.toLowerCase()}`}>{label(selected.status)}</span><dl><dt>Current owner</dt><dd>{selected.owner || 'Unconfirmed'}</dd><dt>Current deadline</dt><dd>{deadline(selected)}</dd></dl><h3>Why this status?</h3><p className="explanation">{selected.decision_explanation}</p><h3>Deadline history</h3>{selected.deadline_history.length ? selected.deadline_history.map((d,i)=><div className="history" key={i}><strong>{d.deadline_text}</strong><p>{date(d.normalized_deadline)} · {d.accepted ? 'Accepted' : 'Earlier commitment retained'}</p><small>{d.assumption}</small></div>) : <p className="muted">No explicit deadline in the evidence.</p>}<h3>Source evidence</h3>{selected.evidence.map((e,i)=><article className="evidence" key={i}><span className="eyebrow">{sources.find(s=>s.source_id===e.source_id)?.source_type || e.type}</span><p>{date(e.timestamp)} · {e.author}</p><blockquote>{e.evidence_text}</blockquote><button onClick={()=>openSource(e.source_id)}>Open original source <ArrowUpRight size={14}/></button></article>)}</>}</aside></div>}</div>
}
